server:
  port: 8000


spring:
  mvc:
    static-path-pattern: /static/**

    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://web-study.csbruw3zvnas.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220929-HDH
      username: HDH
      password: 1q2w3e4r!

mybatis:
  mapper-locations:
    - /mappers/*.xml
